### PR TITLE
Engr metric

### PR DESCRIPTION
**Pull request by khauersp**
This isn't the best solution but it's working for now

### CODE REVIEW

**Comment by GraysonNocera** [comment]
So we're not getting rate limited?

**Comment by khauersp** [comment]
No we are still

**Comment by GraysonNocera** [comment]
> No we are still

any conceivable way of fixing that? Especially if we wanna scale this, that'll be tough.

**Comment by khauersp** [comment]
Yeah I mean I think adding in graphql will help a lot. Graphql could cut our rest api calls in half

**Comment by khauersp** [comment]
Combined with graphql implementation #14 will be merged with that

**Pull request closed without merging**
