### PR TITLE
CI implementation ready. linter and build

### PR DESCRIPTION
**Pull request by b4yuan**

### CODE REVIEW

**Review by khauersp — APPROVED** [review]
Looks good. lint is really annoying so maybe the linter can help

**Review by GraysonNocera — COMMENTED** [review]
What is the server_stub folder for?

**Comment by GraysonNocera** [comment]
> 

Try deleting it and see if the linter still passes. If so, we can probably delete it. If all else fails, we can look back at the commit and add it again if it is crucial

**Review by GraysonNocera — APPROVED** [review]
This is huge. You a real one fr fr

**Pull request merged**
