### PR TITLE
Begin api

### PR DESCRIPTION
**Pull request by GraysonNocera**

### CODE REVIEW

**Comment by khauersp** [comment]
So will this be the API implementation or will we have to add more to it later on?

**Comment by GraysonNocera** [comment]
> So will this be the API implementation or will we have to add more to it later on?

From my understanding, this is just a template. I believe we will need to add a good bit to this (as well as read through it several types to figure out what it's actually doing), but I believe it is a good start. I didn't change anything in it except just running the CLI command to auto-generate these files.

**Review by khauersp — APPROVED** [review]
Sounds good it's a great start though

**Comment by GraysonNocera** [comment]
I'm closing this until we understand it and until I know that the problem with request being deprecated isn't a huge issue. I'll try to add comments and stuff to this to understand it.

**Pull request closed without merging**
